#!/bin/sh
#
#  Copyright (C) 2014  LoVullo Associates, Inc.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
# #

cd "$( dirname "$0" )"

outdir=xspec
index="$outdir/index.html"

htmlindex()
{
  cat >> "$index"
}

# xspec's output dir
mkdir -p "$outdir"
rm -f "$index"

htmlindex <<EOH
<html>
  <head>
    <title>Test Index</title>
  </head>
  <body>
    <h1>Test Index</h1>
    <ul>
EOH

find . -name '*.xspec' | while read spec; do
  ../tools/xspec/bin/xspec.sh "$spec"

  result="$( basename "$spec" .xspec )-result.html"
  printf '      <li><a href="%s">%s</a></li>' "$result" "$spec" \
    | htmlindex
done

htmlindex <<EOF
    </ul>
  </body>
</html>
EOF

